#Variables(Para utilizarlas en el make uso la siguiente sintaxis "$(Nombre de la Variable)")

OBJETOS = Ej_2.o Sumar.o Presentar.o

BINARY = Programa #Nombre del programa

CFLAGS= -g -Wall #Parametros para el compilador

all: Programa 
	#Regla General ejecuta a "Programa"


Programa:$(OBJETOS) 
	
	gcc -o $(BINARY) $(OBJETOS) 
	#"Programa" es en nombre del ejecutable y va despues de -o

Ej_2.o:Ej_2.c funciones.h
	
	gcc $(CFLAGS) -c Ej_2.c 

Sumar.o:Sumar.c funciones.h
	
	gcc $(CFLAGS) -c Sumar.c

Presentar.o:Presentar.c funciones.h
	
	gcc $(CFLAGS) -c 
Presentar.c
clean:
	
	rm -f $(BINARY) $(OBJETOS)  
	
	#Elimina programa y cualquier archivo de tipo objeto "-f":Omite confirmacion
